apiVersion: v1
kind: Service
metadata:
  name: {{ include "versioning-api.fullname" . }}
  labels:
    {{- include "versioning-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- $ports := split "," .Values.service.ports }}
    {{- range $index, $port := $ports }}
    - name: http{{ $index | replace "_" "-" }}
      port: {{ $port }}
      protocol: TCP
      targetPort: http
    {{- end }}
  selector:
    {{- include "versioning-api.selectorLabels" . | nindent 4 }}
